name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        
    - run: flutter create myapp --platforms android
    
    - run: |
        cd myapp
        echo "
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  home: Scaffold(
    appBar: AppBar(title: Text('Test App')),
    body: Center(child: Text('Hello World')),
  ),
));" > lib/main.dart
        
    - run: cd myapp && flutter build apk --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: myapp/build/app/outputs/flutter-apk/app-release.apk