name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter create myapp
      - run: cd myapp && flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: ppa
          path: myapp/build/ppa/outputs/flutter-apk/app-debug.apk